# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7cc895d4cbeb275acc618b5455e5bb705795c376116532c5456ca7bba275d2f585febc45c5309b77519bc7acd88d6f0a1948a8fa9d6e6afffc399e2d298303
  sfdc_user_name: tihopkins@devsbx.deloitte.ca
  sfdc_password: devsbxPast0r1us
  sfdc_security_token: 4cvbK3LHAg4htHjgBy4AUt9NT
  sfdc_client_id: 3MVG9sG9Z3Q1Rlbe4pI4lugLADwHp_ChbqMZ9GhXNLINzapywHXN7iu9.fqhPz6yS0XKJPOmnIw==
  sfdc_client_secret: 9201894287742747201


test:
  secret_key_base: 6a1a16cc83e6c171743e078a19c233c72fcc4d550847a01e54568a25828462c048ab6a476b252f4d4386cc24001038b46edc251c72060162fce74d0650035147
  sfdc_user_name: tihopkins@devsbx.deloitte.ca
  sfdc_password: devsbxPast0r1us
  sfdc_security_token: 4cvbK3LHAg4htHjgBy4AUt9NT
  sfdc_client_id: 3MVG9sG9Z3Q1Rlbe4pI4lugLADwHp_ChbqMZ9GhXNLINzapywHXN7iu9.fqhPz6yS0XKJPOmnIw==
  sfdc_client_secret: 9201894287742747201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sfdc_user_name: tihopkins@devsbx.deloitte.ca
  sfdc_password: devsbxPast0r1us
  sfdc_security_token: 4cvbK3LHAg4htHjgBy4AUt9NT
  sfdc_client_id: 3MVG9sG9Z3Q1Rlbe4pI4lugLADwHp_ChbqMZ9GhXNLINzapywHXN7iu9.fqhPz6yS0XKJPOmnIw==
  sfdc_client_secret: 9201894287742747201